services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_server
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST = db
      - MYSQL_USER = root
      - MYSQL_PASSWORD = rootpassword
      - MYSQL_DATABASE = testdb
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
